@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Mar 25 10:37:57 +0000 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CE869_CPU_SYS_tb_behav -key {Behavioral:sim_1:Functional:CE869_CPU_SYS_tb} -tclbatch CE869_CPU_SYS_tb.tcl -view M:/pc/desktop/HighLevelLogic/Assigment2/Assigment2/CE869_CPU_SYS_tb_behav.wcfg -log simulate.log"
call xsim  CE869_CPU_SYS_tb_behav -key {Behavioral:sim_1:Functional:CE869_CPU_SYS_tb} -tclbatch CE869_CPU_SYS_tb.tcl -view M:/pc/desktop/HighLevelLogic/Assigment2/Assigment2/CE869_CPU_SYS_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
